// <auto-generated>
//  automatically generated by table tool, do not modify
// </auto-generated>
using Framework;
using System.Collections.Generic;

namespace Chanto
{
	public class ConfigManager : Singleton<ConfigManager>
    {
        private Dictionary<string, byte[]> dataTableAssets = new Dictionary<string, byte[]>(100);
        public Dictionary<string, byte[]> DataTableAssets { get { return dataTableAssets; } }

        /// <summary>
        /// 判断表名是否合法
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <returns>true-合法, false-不合法</returns>
        public bool IsValidTable(string tableName)
        {
            bool isValid = false;

            switch (tableName)
            {
                case "atlas": { isValid = true; break; }
                case "sprites": { isValid = true; break; }

                default:
                    break;
            }

            return isValid;
        }
    }
}