// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using FlatBuffers;
using LS.Table;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Chanto
{
    public class Hot_sprites_extendTable : SpritesTable
    {
        #region Framework Method

        protected override string GetTableFileName()
        {
            return "hot_sprites_extend";
        }

        protected override string GetDataFileName()
        {
            return "hot_sprites_extend.bytes";
        }

        protected override string GetIndexFileName()
        {
            return "hot_sprites_extend_ids";
        }

        #endregion Framework Method
    }
}